- name: Download and install k3s
  ansible.builtin.get_url:
    url: "https://get.k3s.io"
    dest: /tmp/get_k3s.sh
    mode: "0755"

- name: Run k3s installation script
  ansible.builtin.command: /tmp/get_k3s.sh --disable traefik
  register: k3s_install_output
  args:
    creates: /usr/local/bin/k3s
