- name: Setup k3s and helm on Linux
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Gather user shell
      ansible.builtin.set_fact:
        user_shell: "{{ ansible_facts.shell | default(ansible_env.SHELL) }}"
  roles:
    - role: install_k3s
